contacts
Wiecek-K/Jezdzcy-Szopokalipsy pull request #13
Opened 2022-12-18 22:40 UTC by KarolKowalewicz

kontakty

2022-12-18 22:58 UTC, Wiecek-K reviewed
do poprawy, notatki slack

2022-12-19 16:32 UTC, Wiecek-K requested changes
ty chyba ja tą opcje powinienem klikać jak wymagam żeby coś było zmienione przed merge
A więc klikam tę opcję xD

2022-12-22 15:21 UTC, KamilCzachor approved these changes

2022-12-22 16:11 UTC, Wiecek-K approved these changes

2022-12-22 16:11 UTC, merged